'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18063
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("login.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to END USER LICENSE AGREEMENT
        '''
        '''	This End User License Agreement (“Agreement”), effective _____,  is between Industry Systems Software, Inc. (“ISSI”) and _______ (“Licensee”) for use of an ISSI software product.  The parties agree as follows.
        '''
        '''1.	DEFINITIONS
        '''
        '''License Term: The “License Term” means the period beginning on the effective date and ending upon termination of the Project.
        '''
        '''Permitted Computers: “Permitted Computers” means servers, PC tablets, and other equipment provided by ISSI. 
        '''
        '''Product:  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _060823eula() As String
            Get
                Return ResourceManager.GetString("_060823eula", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''use [!!dbName!!]
        '''
        '''exec sp_grant_publication_access @publication = N&apos;!!dbName!!&apos;, @login = N&apos;!!MachineName!!\Daqart_Agent&apos;
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property addPAL() As String
            Get
                Return ResourceManager.GetString("addPAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''use [!!dbName!!]
        '''
        '''exec sp_grant_publication_access @publication = N&apos;!!dbName!!&apos;, @login = N&apos;daqart_sa&apos;
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property addPALSQL() As String
            Get
                Return ResourceManager.GetString("addPALSQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to USE [!!dbName!!]
        '''
        '''CREATE USER [!!MachineName!!\Daqart_Agent] FOR LOGIN [!!MachineName!!\Daqart_Agent]
        '''
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property addRoles() As String
            Get
                Return ResourceManager.GetString("addRoles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to USE [!!dbName!!]
        '''
        '''CREATE USER [daqart_sa] FOR LOGIN [daqart_sa]
        '''
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property addRolesSQL() As String
            Get
                Return ResourceManager.GetString("addRolesSQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to USE [master]
        '''
        '''CREATE DATABASE !!SiteName!!_Daqument001
        '''.
        '''</summary>
        Friend ReadOnly Property createDaqument001DB() As String
            Get
                Return ResourceManager.GetString("createDaqument001DB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to USE [!!SiteName!!_Daqument001]
        '''
        '''SET ANSI_NULLS ON
        '''
        '''SET QUOTED_IDENTIFIER ON
        '''
        '''IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[document_store]&apos;) AND type in (N&apos;U&apos;))
        '''BEGIN
        '''CREATE TABLE [dbo].[document_store](
        '''	[ID] [int] IDENTITY(1,1) NOT NULL,
        '''	[TS] [datetime] NULL,
        '''	[DocumentID] [int] NOT NULL,
        '''	[DocumentImage] [image] NULL,
        ''' CONSTRAINT [PK_document_store] PRIMARY KEY CLUSTERED 
        '''(
        '''	[ID] ASC
        ''')WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
        ''') ON [PRIMARY]
        '''END
        '''
        '''
        '''SET A [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property createDaqument001Tables() As String
            Get
                Return ResourceManager.GetString("createDaqument001Tables", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to USE [master]
        '''
        '''CREATE DATABASE !!SiteName!!_Daqument
        '''.
        '''</summary>
        Friend ReadOnly Property createDaqumentDB() As String
            Get
                Return ResourceManager.GetString("createDaqumentDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to USE [!!SiteName!!_Daqument]
        '''
        '''
        '''SET ANSI_NULLS ON
        '''SET QUOTED_IDENTIFIER ON
        '''IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[drawing_layers]&apos;) AND type in (N&apos;U&apos;))
        '''BEGIN
        '''CREATE TABLE [dbo].[drawing_layers](
        '''	[MUID] [nvarchar](150) NOT NULL,
        '''	[DrawingMUID] [nvarchar](150) NOT NULL,
        '''	[layerRevDate] [datetime] NOT NULL,
        '''	[LastUserMUID] [nvarchar](150) NOT NULL,
        '''	[layerStatus] [int] NOT NULL,
        '''	[DateCreated] [datetime] NOT NULL,
        '''	[layerDescription] [nvarchar](max) NULL,
        '''	[ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property createDaqumentTables() As String
            Get
                Return ResourceManager.GetString("createDaqumentTables", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to USE [master]
        '''
        '''CREATE DATABASE !!SiteName!!_ServerDB
        '''.
        '''</summary>
        Friend ReadOnly Property createServerDB() As String
            Get
                Return ResourceManager.GetString("createServerDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_transparent2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_transparent2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to use [!!SiteName!!_Daqument]
        '''exec sp_replicationdboption @dbname = N&apos;!!SiteName!!_Daqument&apos;, @optname = N&apos;merge publish&apos;, @value = N&apos;true&apos;
        '''
        '''-- Adding the merge publication
        '''use [!!SiteName!!_Daqument]
        '''exec sp_addmergepublication @publication = N&apos;!!SiteName!!_Daqument&apos;, @description = N&apos;Merge publication of database &apos;&apos;!!SiteName!!_Daqument&apos;&apos; from Publisher &apos;&apos;!!PUB!!&apos;&apos;.&apos;, @sync_mode = N&apos;character&apos;, @retention = 14, @allow_push = N&apos;true&apos;, @allow_pull = N&apos;true&apos;, @allow_anonymous = N&apos;true&apos;, @enabled_for_inter [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PublishDaqument() As String
            Get
                Return ResourceManager.GetString("PublishDaqument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to use [!!SiteName!!_Daqument001]
        '''exec sp_replicationdboption @dbname = N&apos;!!SiteName!!_Daqument001&apos;, @optname = N&apos;merge publish&apos;, @value = N&apos;true&apos;
        '''
        '''-- Adding the merge publication
        '''use [!!SiteName!!_Daqument001]
        '''exec sp_addmergepublication @publication = N&apos;!!SiteName!!_Daqument001&apos;, @description = N&apos;Merge publication of database &apos;&apos;!!SiteName!!_Daqument001&apos;&apos; from Publisher &apos;&apos;!!PUB!!&apos;&apos;.&apos;, @sync_mode = N&apos;character&apos;, @retention = 14, @allow_push = N&apos;true&apos;, @allow_pull = N&apos;true&apos;, @allow_anonymous = N&apos;true&apos;, @en [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PublishDaqument001() As String
            Get
                Return ResourceManager.GetString("PublishDaqument001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to use [!!SiteName!!_ServerDB]
        '''exec sp_replicationdboption @dbname = N&apos;!!SiteName!!_ServerDB&apos;, @optname = N&apos;merge publish&apos;, @value = N&apos;true&apos;
        '''
        '''-- Adding the merge publication
        '''use [!!SiteName!!_ServerDB]
        '''exec sp_addmergepublication @publication = N&apos;!!SiteName!!_ServerDB&apos;, @description = N&apos;Merge publication of database &apos;&apos;!!SiteName!!_ServerDB&apos;&apos; from Publisher &apos;&apos;!!PUB!!&apos;&apos;.&apos;, @sync_mode = N&apos;character&apos;, @retention = 14, @allow_push = N&apos;true&apos;, @allow_pull = N&apos;true&apos;, @allow_anonymous = N&apos;true&apos;, @enabled_for_inter [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PublishServerDB() As String
            Get
                Return ResourceManager.GetString("PublishServerDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to USE [!!SiteName!!_ServerDB]
        '''
        '''SET ANSI_NULLS ON
        '''SET QUOTED_IDENTIFIER ON
        '''IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[bugsug]&apos;) AND type in (N&apos;U&apos;))
        '''BEGIN
        '''CREATE TABLE [dbo].[bugsug](
        '''	[MUID] [nvarchar](150) NOT NULL,
        '''	[TS] [datetime] NULL,
        '''	[ClientMUID] [int] NULL,
        '''	[Type] [int] NULL,
        '''	[Description] [nvarchar](500) NULL,
        '''	[FName] [nvarchar](50) NULL,
        '''	[MI] [nvarchar](1) NULL,
        '''	[LName] [nvarchar](50) NULL,
        '''	[Email] [nvarchar](50) NULL,
        '''	[Phone] [nvarchar](50) N [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ServerDBTables() As String
            Get
                Return ResourceManager.GetString("ServerDBTables", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to use [!!dbName!!]
        '''exec sp_startpublication_snapshot @publication = &apos;!!dbName!!&apos; .
        '''</summary>
        Friend ReadOnly Property sp_startpublication_snapshot() As String
            Get
                Return ResourceManager.GetString("sp_startpublication_snapshot", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
